### PR TITLE
rebuild

### PR DESCRIPTION
**Pull request by beckermr**
This PR rebuilds for python 3.7. Closes #7

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
This is blocked on a bug in the upstream package. Pinging @conda-forge/lagranto for help!

**Comment by beckermr** [comment]
I made an issue here and removed the test that blocked this.

**Comment by beckermr** [comment]
@conda-forge/lagranto this pr is ready to merge. 

I had to remove the tests for python 2 due to a bug in the test suite. I made an issue on this repo since I do not have access to the upstream repo. I also had to limit the numpy version for python 2.

**Comment by beckermr** [comment]
The numpy limit for python 2 is related to type checking done in later versions of numpy on the `Path` objects used for files in the code.

**Comment by beckermr** [comment]
@conda-forge/core I cannot seem to turn off appveyor for the non-existent windows build on this repo. I have tried rerendering it more than once, Is there a setting somewhere that one of y'all can flip or something?

**Comment by mariusvniekerk** [comment]
It's mostly harmless. Appveyor is weird sometimes

**Comment by jakirkham** [comment]
@conda-forge-admin, please update circle as code checkout is [failing]( https://circleci.com/gh/conda-forge/lagranto-feedstock/109 ).

**Comment by jakirkham** [comment]
Triggered a [rebuild on CircleCI]( https://circleci.com/workflow-run/d138baab-16c4-4d68-82e1-6fe0b8325469 ).

**Pull request merged**
